[build]
  # 发布目录 - 整个项目根目录
  publish = "."
  
  # 不需要构建命令，因为这是纯静态网站
  command = ""

[build.environment]
  # Node.js版本（如果需要）
  NODE_VERSION = "18"

# 重定向规则，确保SPA路由正常工作
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["!"], Exception = ["!", "/text-generator/*", "/image-generator/*", "/csv-generator/*", "/*.html", "/*.css", "/*.js", "/*.png", "/*.jpg", "/*.svg", "/*.ico"]}

# 头部设置 - 增强安全性和性能
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 表单处理（如果需要）
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true